// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package types

// CalculateRequest defines model for CalculateRequest.
type CalculateRequest struct {
	// Order Number of items the customer ordered.
	Order int `json:"order"`
}

// CalculateResponse defines model for CalculateResponse.
type CalculateResponse struct {
	// Overshoot `total_items - order`. Zero when the order is met exactly.
	Overshoot int `json:"overshoot"`

	// Packs The pack combination. Sorted by size descending.
	Packs []PackCount `json:"packs"`

	// TotalItems Sum of `size * count` across all packs.
	TotalItems int `json:"total_items"`

	// TotalPacks Sum of `count` across all packs.
	TotalPacks int `json:"total_packs"`
}

// ErrorResponse Single error envelope used by every non-2xx response. The `code`
// is a stable machine-readable slug; the `message` is human-readable
// and may include input echo for debuggability; the `request_id`
// ties the response to log lines.
type ErrorResponse struct {
	// Code Stable machine-readable error slug.
	Code string `json:"code"`

	// Message Human-readable error message.
	Message string `json:"message"`

	// RequestId Request id (echoes the `X-Request-Id` request/response header).
	RequestId string `json:"request_id"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status Either `ok` (liveness) or `ready` (readiness).
	Status string `json:"status"`
}

// PackCount A bucket of a single pack size used in a calculation result.
type PackCount struct {
	// Count Number of packs of this size used in the result.
	Count int `json:"count"`

	// Size Pack size in items.
	Size int `json:"size"`
}

// PackSet Current pack-size configuration plus its opaque version.
type PackSet struct {
	// Sizes Pack sizes, sorted by size descending. Normalized server-side.
	Sizes []int `json:"sizes"`

	// Version Opaque, server-assigned version (ULID). Pass to PUT as `If-Match` for optimistic concurrency.
	Version string `json:"version"`
}

// PutPacksRequest Request body for `PUT /api/v1/packs`. The server normalizes and de-duplicates.
type PutPacksRequest struct {
	// Sizes Pack sizes. Must be non-empty, all positive, and contain no duplicates.
	Sizes []int `json:"sizes"`
}

// PutPacksParams defines parameters for PutPacks.
type PutPacksParams struct {
	// IfMatch Opaque version returned by a prior GET or PUT. When present, the write succeeds only if the current version matches.
	IfMatch *string `json:"If-Match,omitempty"`
}

// CalculateJSONRequestBody defines body for Calculate for application/json ContentType.
type CalculateJSONRequestBody = CalculateRequest

// PutPacksJSONRequestBody defines body for PutPacks for application/json ContentType.
type PutPacksJSONRequestBody = PutPacksRequest
